export const FETCH_PIZZAS_START = "FETCH_PIZZAS_START";
export const FETCH_PIZZAS_SUCCESS = "FETCH_PIZZAS_SUCCESS";
export const FETCH_PIZZAS_FAILURE = "FETCH_PIZZAS_FAILURE";

export const LOAD_MORE_PIZZAS_START = "LOAD_MORE_PIZZAS_START";
export const LOAD_MORE_PIZZAS_SUCCESS = "LOAD_MORE_PIZZAS_SUCCESS";
export const LOAD_MORE_PIZZAS_FAILURE = "LOAD_MORE_PIZZAS_FAILURE";

export const FETCH_PIZZA_BY_ID_START = "FETCH_PIZZA_BY_ID_START";
export const FETCH_PIZZA_BY_ID_SUCCESS = "FETCH_PIZZA_BY_ID_SUCCESS";
export const FETCH_PIZZA_BY_ID_FAILURE = "FETCH_PIZZA_BY_ID_FAILURE";

export const ADD_PIZZA_TO_BASKET = "ADD_PIZZA_TO_BASKET";

export const SEARCH_PIZZA = "SEARCH_PIZZA";

export const FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

export const REMOVE_PIZZA_FROM_BASKET = "REMOVE_PIZZA_FROM_BASKET";
export const CLEAN_BASKET = "CLEAN_BASKET";
export const BASKET_CHECKOUT = "BASKET_CHECKOUT";
